### PR TITLE
Allow underscores in numbers.

### PR DESCRIPTION
**Pull request by mojombo**
Makes these possible. Addresses #295.

```
# integers
1_000
5_349_221
1_2_3_4_5     # valid but inadvisable

# floats
9_224_617.445_991_228_313
1e4_000_000
```

### CODE REVIEW

**Comment by ChristianSi** [comment]
:+1:

**Comment by mojombo** [comment]
@BurntSushi Any further comments on this? Otherwise I'll merge it in.

**Comment by mwanji** [comment]
Isn't `1e4_000_000` outside of the range of a float?

**Comment by mojombo** [comment]
@mwanji Yes, that's true! I'll push a fix.

**Comment by mojombo** [comment]
@BurntSushi I'd love to see your +1 on this before I merge it.

**Comment by BurntSushi** [comment]
@mojombo :+1:

**Comment by fbernier** [comment]
Sorry for reviving this old PR but I think something should be clarified:

`Each underscore must be surrounded by at least one digit.`

Does that mean that `45_` should be valid? If not, it should be mentioned that it can't start or end with an underscore.

**Comment by mojombo** [comment]
@fbernier Ah, I see what you're saying. I guess I thought "surrounded" implied a digit on both sides. How about:

`Each underscore must be surrounded by at least one digit on each side.`

**Comment by fbernier** [comment]
Sounds good to me!

**Pull request merged**
