### PR TITLE
Disallow signed zeros as integers

### PR DESCRIPTION
**Pull request by pradyunsg**
Resolves (partially) #389.

### CODE REVIEW

**Comment by ChristianSi** [comment]
I don't like this proposed change. It shouldn't matter whether I write zero as "0", "+0", or "-0".

If forbidding "-0", why not forbidding "+0" as well? This is all unnecessary fiddling. Leave the spec as is (in this regard).

**Comment by pradyunsg** [comment]
Umm, only 0 is valid. -0 and +0 are not. That's what a signed zero is. A zero prefixed with a sign. I'm proposing this.

I thought the language I used was clear. Is it not?

I would like TOML to take a stand in the regard and the proposed one is something I'm more comfortable with than the alternatives. Ideally, floats may have signed 0 based on implementation but yeah integers are better off unsigned. I honestly don't see why anyone would want to use signed zeros in configuration.

**Comment by StefanKarpinski** [comment]
> Umm, only 0 is valid. -0 and +0 are not. That's what a signed zero is.

That’s not what a signed zero is – a signed zero is a distinct zero value whose sign is negative, the syntax is incidental. It’s completely standard in programming languages and data formats to allow + signs on numeric literals and to parse integer `-0` as the same value as `0` and `+0`.

This is not a very controversial position: it is what basically every language and data format does.

**Comment by pradyunsg** [comment]
@StefanKarpinski Let's keep the discussion at #389? :)

**Comment by mojombo** [comment]
I'm closing this in favor of #504 which has a few tweaks I want and doesn't conflict with master.

**Pull request closed without merging**
