### PR TITLE
Reorganize the repository

### PR DESCRIPTION
**Pull request by pradyunsg**
With toml-lang/toml.io#1 solved, we now have a new place to put the released versions TOML specifications as well as their translations.

This PR drops `examples/` `versions/` and `tests/` from this repository, and separates the current TOML specification from the README of this repository.

### CODE REVIEW

**Comment by pradyunsg** [comment]
> versions/en/toml-v1.0.0-rc.1.md → toml.md

GitHub is anchoring things wrong -- I cut-pasted that out of the README.md file. >.<

**Comment by pradyunsg** [comment]
Alrighty, this looks good to go! Not waiting on reviews since... there isn't much to review here, and we can definitely address any concerns in a follow up. :)

**Comment by pradyunsg** [comment]
Oh, and I expect this to break *all* the existing PRs which are updating the language in the README. However, none of the PRs are critical path for TOML 1.0, so it's fine.

**Comment by eksortso** [comment]
Overall, thanks for doing this. You're a saint.

**Pull request merged**
