### PR TITLE
Create starship

### PR DESCRIPTION
**Pull request by nczaw**

### CODE REVIEW

**Comment by pradyunsg** [comment]
@nczaw Hi! Could you elaborate on what this PR is about?

**Comment by marzer** [comment]
@pradyunsg it looks like a configuration file for [this (https://starship.rs/), though the relevance it has for toml-lang is not at all apparent to me.

**Comment by eksortso** [comment]
Nothing personal, but we already have a PR for a fancy graphical upgrade in #909, and it's more germane to the project than what this would be for.

**Comment by pradyunsg** [comment]
Closing this out since it's unclear what this is for. @nczaw Please feel welcome to comment with more context. :)

**Pull request closed without merging**
