### PR TITLE
Update toml.abnf

### PR DESCRIPTION
**Pull request by LongTengDao**

### CODE REVIEW

**Comment by marzer** [comment]
Aren't ABNFs case-insensitive? If so, the comment was correct already.

**Comment by marzer** [comment]
Also, from RFC 3339:

> NOTE: Per [ABNF] and ISO8601, the "T" and "Z" characters in this
      syntax may alternatively be lower case "t" or "z" respectively.

**Comment by LongTengDao** [comment]
> Aren't string literals in ABNFs case-insensitive? If so, the comment was correct already.

Oh! Thank you to figure out! Then my implementation didn't do right thing about `T` and `Z` from the beginning...

**Comment by marzer** [comment]
@LongTengDao neither did mine until recently 😅

**Comment by LongTengDao** [comment]
> @LongTengDao neither did mine until recently 😅

How did you notice that... T_T @marzer

**Comment by marzer** [comment]
Good question, I don't remember. I _think_ it was one of the more recent tests added to the toml-test suite, but I can't be sure.

**Pull request closed without merging**
