### PR TITLE
Clarify that line-ending backslashes are unescaped

### PR DESCRIPTION
**Pull request by goodmami**
Part of #728

### CODE REVIEW

**Comment by eksortso** [comment]
LGTM. This will close #728. Thank you!

**Comment by ChristianSi** [comment]
Wow, that was fast :smiley:

**Comment by goodmami** [comment]
:) The diff looks bigger now but it's just the reflowing.

Thanks for the feedback!

**Comment by pradyunsg** [comment]
Thanks for the PR @goodmami ,and for your inputs here @eksortso and @ChristianSi!

**Pull request merged**
