### PR TITLE
Include an \xHH escape code sequence

### PR DESCRIPTION
**Pull request by eksortso**
Per a conversation in #622, this PR adds a two-character `\x` escape code sequence for the first 256 Unicode code points. This provides a short explicit sequence for, among other code points: ASCII characters, certain control characters, and whitespace characters such as tab (`\x09`) and space (`\x20`) that need visible representation without resorting to longer `\u` and `\U` codes. Such sequences are commonly found in languages that also support the `\u` and `\U` codes for Unicode.

### CODE REVIEW

**Comment by ChristianSi** [comment]
Looks good, I'm all for merging!

**Comment by pradyunsg** [comment]
Hmm... this seems to have a slightly messed up history here.

**Comment by eksortso** [comment]
I hope I didn't mess anything up. I was trying to bring it up to date. It's still for after v1.0.0, so if a new PR is in order, I can replace this one when the time is right.

**Comment by Ekkarat30** [comment]
Excellent to get the writing access.

**Comment by eksortso** [comment]
Since the history on this PR got messed up, I am replacing it with a new one, #796. The changes to the text (from when it was branched) should be identical to the changes done here.

**Pull request closed without merging**
