### PR TITLE
Took a shot at logos

### PR DESCRIPTION
**Pull request by robmuh**
Yeah, my feelings won't be hurt if rejected, figured what the hell.

### CODE REVIEW

**Comment by BinaryMuse** [comment]
but none of them include @mojombo's face

**Comment by Hrxn** [comment]
Well, every serious project needs a logo, right?

**Comment by adamvoss** [comment]
To save inspecting the diff, here is the logo in this PR:

Proposed logo

**Comment by adamvoss** [comment]
> Well, every serious project needs a logo, right?

Among comparable projects (CSON, Hjson, JSON, JSON5, and YAML).  Only CSON doesn't have a logo.  I know because I gathered logos for https://json-schema-everywhere.github.io/.

**Comment by mojombo** [comment]
Love it! Thanks for the contribution!!!

**Pull request merged**
