### PR TITLE
append the Japanese translation of v0.5.0

### PR DESCRIPTION
**Pull request by minoritea**
I made a new Japanese translation based on the v0.5.0 spec.

### CODE REVIEW

**Comment by minoritea** [comment]
Is there some blocking issue?

**Comment by pradyunsg** [comment]
Hey @minoritea!

I'm not familiar with Japanese, so I can't be reviewing this in any substantial manner. I'll go ahead and merge this in good faith that you've have done the right thing here. :)

> Is there some blocking issue?

Mostly just that none of the maintainers got around to click the merge button. :)

**Comment by pradyunsg** [comment]
Thanks for the contribution! ✨

**Comment by minoritea** [comment]
Thank you for merging the request.

Maybe we need a second opinion for the translation but now I don't prepare.

If someone complains about the translation, please let me know to fix it.

Thanks,

**Comment by pradyunsg** [comment]
> Maybe we need a second opinion for the translation

That would definitely be nice. If you could get someone you know to read it, that'd work too.

> If someone complains about the translation, please let me know to fix it.

Definitely. :)

**Pull request merged**
